security:
  oauth2:
    client:
      clientId: e2a746fc-cb1a-49c3-9436-67004117b039
      clientSecret: 25c9a32b-45a9-447a-a7e3-3a28d6a6834e
    resource:
      tokenInfoUri: ${herodotus.platform.token-info-uri}
      userInfoUri: ${herodotus.platform.user-info-uri}