herodotus:
  integration:
    social:
      easemob:
        url: http://a1.easemob.com/1131190611046482/braineex
        client-id: YXA6rP4qUIv0EemF4THv1mHhfQ
        client-secret: YXA6hqKIZ0Z8xXn8XGUbtLWQ1vWNEUo