herodotus:
  environment:
    redis-host: 127.0.0.1
    redis-port: 6379
    redis-password:
    kafka-bootstrap-servers: 127.0.0.1:9092
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/herodotus
    username: ENC(VQOHWBUv8CXJE50zyMEhCozzElZhNbJ8suinU7Ph651G1xl4QPweElrhtXP4V0T8)
    password: ENC(VQOHWBUv8CXJE50zyMEhCozzElZhNbJ8suinU7Ph651G1xl4QPweElrhtXP4V0T8)
    show-sql: false
    logstash-server-addr: 127.0.0.1:5044
    gateway-server-addr: http://localhost:8847
  initialization:
    hibernate-ddl-auto: update
  switch:
    swagger:
      enabled: false

  management:
    log-center:
      server-addr: ${herodotus.environment.logstash-server-addr}
      loggers:
        cn.herodotus.eurynome: info
        org.springframework.security: info
        com.alibaba.nacos.client.naming: error
        com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty: error
        # 关闭不必要的日志
        org.reflections.Reflections: off
        com.alibaba.nacos.client: error
        com.alibaba.nacos.common.remote.client: error
        com.ulisesbocchio: error
jasypt:
  encryptor:
    password: ${JASPYT_HOME:2bda7d3a-dba1-45a4-b08e-cbd731a0418e}