version: "3"
services:
  monitor:
    image: eurynome-cloud-platform-monitor:latest
    build:
      context: ../../context
      dockerfile: ./development/Config-Monitor-Dockerfile
    container_name: monitor
    ports:
      - 8845:8845
  upms:
    image: eurynome-cloud-upms-rest:latest
    build:
      context: ../../context
      dockerfile: ./development/Config-Upms-Dockerfile
    container_name: upms
    ports:
      - 7070:7070
    depends_on:
      - monitor

  gateway:
    image: eurynome-cloud-platform-gateway:latest
    build:
      context: ../../context
      dockerfile: ./development/Config-Gateway-Dockerfile
    container_name: gateway
    ports:
      - 8847:8847
    depends_on:
      - monitor

  uaa:
    image: eurynome-cloud-platform-uaa:latest
    build:
      context: ../../context
      dockerfile: ./development/Config-Uaa-Dockerfile
    container_name: uaa
    ports:
      - 8846:8846
    depends_on:
      - upms
      - monitor