herodotus:
  platform:
    endpoint:
      gateway-address: ${herodotus.environment.gateway-server-addr}
      uaa-service-uri: ${herodotus.platform.endpoint.gateway-address}/eurynome-cloud-uaa
      upms-service-uri: ${herodotus.platform.endpoint.gateway-address}/eurynome-cloud-upms-ability
      access-token-uri: ${herodotus.platform.endpoint.uaa-service-uri}/oauth/token
      user-authorization-uri: ${herodotus.platform.endpoint.uaa-service-uri}/oauth/authorize
      token-info-uri: ${herodotus.platform.endpoint.uaa-service-uri}/oauth/check_token
      user-info-uri: ${herodotus.platform.endpoint.uaa-service-uri}/identity/profile
    swagger:
      enabled: ${herodotus.switch.swagger.enabled}
