spring:
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates

springdoc:
  api-docs:
    resolve-schema-properties: true
  swagger-ui:
    enabled: ${herodotus.switch.swagger.enabled}
    disable-swagger-default-url: true
    operations-sorter: method
    show-common-extensions: true
    show-extensions: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      app-name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  sentinel:
    enabled: true
  hystrix:
    enabled: false

ribbon:
  ##请求处理的超时时间
  ReadTimeout: 5000
  ##请求连接的超时时间
  ConnectTimeout: 2000
  ##对当前实例的重试次数
  MaxAutoRetries: 1
  ##对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  ##切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  http:
    client:
      enabled: false
  okhttp:
    enabled: true # 用OkHttp代替HttpClient
  eager-load:
    enabled: true
  nacos:
    enabled: false

herodotus:
  platform:
    rest:
      scan:
        enabled: ${herodotus.switch.rest.scan.enabled}