spring:
  redis:
    database: ${herodotus.environment.redis.database}
    host: ${herodotus.environment.redis.host}
    password: ${herodotus.environment.redis.password}
    port: ${herodotus.environment.redis.port}
    timeout: 10000
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 10
        max-wait: 10000
        # 最大空闲连接数 默认8
        max-idle: 10
        # 最小空闲连接数 默认0
        min-idle: 5
    redisson:
      enabled: ${herodotus.switch.redisson.enabled}
      single-server-config:
        address: redis://${spring.redis.password}@${spring.redis.host}:${spring.redis.port}