version: "2"
services:
  sba:
    image: eurynome-cloud-platform-admin:latest
    build:
      context: ../../eurynome-cloud-platform/eurynome-cloud-platform-admin
      dockerfile: Compose-Dockerfile
    container_name: sba
    ports:
      - 8845:8845
  upms:
    image: eurynome-cloud-upms-rest:latest
    build:
      context: ../../eurynome-cloud-services/eurynome-cloud-upms-rest
      dockerfile: Compose-Dockerfile
    container_name: upms
    environment:
      SW_AGENT_FILE: ./skywalking-agent.jar
      SW_AGENT_SERVICE_NAME: eurynome-cloud-platform-gateway
      SW_COLLECTOR_BACKEND_SERVICE: 192.168.101.10:11800
    ports:
      - 7070:7070
    depends_on:
      - sba
    links:
      - sba:sba-service
  gateway:
    image: eurynome-cloud-platform-gateway:latest
    build:
      context: ../../eurynome-cloud-platform/eurynome-cloud-platform-gateway
      dockerfile: Compose-Dockerfile
    container_name: gateway
    environment:
      SW_AGENT_FILE: ./skywalking-agent.jar
      SW_AGENT_SERVICE_NAME: eurynome-cloud-platform-gateway
      SW_COLLECTOR_BACKEND_SERVICE: 192.168.101.10:11800
    ports:
      - 8847:8847
    depends_on:
      - sba
    links:
      - sba:sba-service
  uaa:
    image: eurynome-cloud-platform-uaa:latest
    build:
      context: ../../eurynome-cloud-platform/eurynome-cloud-platform-uaa
      dockerfile: Compose-Dockerfile
    container_name: uaa
    environment:
      SW_AGENT_FILE: ./skywalking-agent.jar
      SW_AGENT_SERVICE_NAME: eurynome-cloud-platform-gateway
      SW_COLLECTOR_BACKEND_SERVICE: 192.168.101.10:11800
    ports:
      - 8846:8846
    depends_on:
      - upms
      - sba
    links:
      - upms:upms-service
      - sba:sba-service