version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    restart: always
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 192.168.101.10
      MYSQL_SERVICE_DB_NAME: luban-cloud-platform
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: itcraftsman
      MYSQL_SERVICE_PASSWORD: itcraftsman
    ports:
      - 8848:8848
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.101.10:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
  sentinel:
    image: bladex/sentinel-dashboard:1.7.1
    container_name: sentinel
    restart: always
    ports:
      - 8849:8858
  elk:
    image: sebp/elk:latest
    container_name: elk
    restart: always
    ports:
      - "5601:5601"
      - "9200:9200"
      - "9300:9300"
      - "5044:5044"
    environment:
      ES_MIN_MEM: 128m
      ES_MAX_MEM: 1024m
    volumes:
      - /D/Development/docker-volumes/es-datas:/data
      - /D/Development/docker-volumes/configs/beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf

