version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    network_mode: "bridge"
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 192.168.101.10
      MYSQL_SERVICE_DB_NAME: luban-cloud-platform
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: itcraftsman
      MYSQL_SERVICE_PASSWORD: itcraftsman
    ports:
      - 8848:8848
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.101.10:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
  upms:
    image: eurynome-cloud-upms-rest:latest
    build:
      context: ../../eurynome-cloud-services/eurynome-cloud-upms-rest
      dockerfile: Compose-Dockerfile
    container_name: upms
    ports:
      - 7070:7070
    depends_on:
      - nacos
      - kafka
    links:
      - nacos:nacos-server
      - kafka:kafka-server
  gateway:
    image: eurynome-cloud-platform-gateway:latest
    build:
      context: ../../eurynome-cloud-platform/eurynome-cloud-platform-gateway
      dockerfile: Compose-Dockerfile
    container_name: gateway
    ports:
      - 8847:8847
    depends_on:
      - nacos
    links:
      - nacos:nacos-server
  uaa:
    image: eurynome-cloud-platform-uaa:latest
    build:
      context: ../../eurynome-cloud-platform/eurynome-cloud-platform-uaa
      dockerfile: Compose-Dockerfile
    container_name: uaa
    ports:
      - 8846:8846
    depends_on:
      - nacos
      - kafka
      - upms
    links:
      - nacos:nacos-server
      - kafka:kafka-server
      - upms:upms-service