version: "3"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    restart: always
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 192.168.101.10
      MYSQL_SERVICE_DB_NAME: luban-cloud-platform
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: itcraftsman
      MYSQL_SERVICE_PASSWORD: itcraftsman
    ports:
      - 8848:8848
    networks:
      - herodotus_standalone_env
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
    networks:
      - herodotus_standalone_env
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.101.10:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - herodotus_standalone_env
  sentinel:
    image: bladex/sentinel-dashboard:1.7.1
    container_name: sentinel
    restart: always
    ports:
      - 8858:8858
    networks:
      - herodotus_standalone_env
  elk:
    image: sebp/elk:latest
    container_name: elk
    restart: always
    ports:
      - "5601:5601"
      - "9200:9200"
      - "9300:9300"
      - "5044:5044"
    environment:
      ES_MIN_MEM: 128m
      ES_MAX_MEM: 512m
      TZ: Asia/Shanghai
    volumes:
      - /D/Development/docker-volumes/es-datas:/data
      - /D/Development/docker-volumes/configs/beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
    networks:
      - herodotus_standalone_env
  oap:
    image: apache/skywalking-oap-server:7.0.0-es7
    container_name: skywalking-oap
    depends_on:
      - elk
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: elk:9200
      TZ: Asia/Shanghai
    networks:
      - herodotus_standalone_env
  ui:
    image: apache/skywalking-ui:7.0.0
    container_name: skywalking-ui
    depends_on:
      - oap
    restart: always
    ports:
      - 8878:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
    networks:
      - herodotus_standalone_env

networks:
  herodotus_standalone_env:
    driver: bridge

