spring:
  jpa:
    database: ${herodotus.environment.database}
    # spring boot2.+后默认使用的是MyISAM引擎,增加如下配置修改为InnoDB模式，
    # 这样不会出现：Specified key was too long; max key length is 1000 bytes 问题
    database-platform: ${herodotus.environment.database-platform}
    open-in-view: true
    show-sql: ${herodotus.environment.show-sql}
    hibernate:
      ddl-auto: ${herodotus.initialization.hibernate-ddl-auto}
      #create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
      #update 如果启动时表格式不一致则更新表，原有数据保留
      #validate 项目启动表结构进行校验 如果不一致则报错
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
        generate_statistics: false
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: cn.herodotus.engine.data.jpa.hibernate.cache.spi.HerodotusRegionFactory
        javax:
          cache:
            missing_cache_strategy: create
        temp:
          use_jdbc_metadata_defaults: false
  sql:
    init:
      enabled: false
      platform: ${herodotus.environment.database-platform}
      continue-on-error: true
      encoding: UTF-8
        username: ${herodotus.environment.username}
        password: ${herodotus.environment.password}
#        data-locations:
#        schema-locations:
  datasource:
    driver-class-name: ${herodotus.environment.driver-class-name}
    url: ${herodotus.environment.url}
    username: ${herodotus.environment.username}
    password: ${herodotus.environment.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # Lowest acceptable connection timeout is 250 ms. Default: 30000 (30 seconds)
      connection-timeout: 5000
      connection-test-query: SELECT 1
      # The minimum allowed value is 10000ms (10 seconds). Default: 600000 (10 minutes)
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 50
      # We strongly recommend setting this value, and it should be at least 30 seconds less than any database or infrastructure imposed connection time limit.
      # Default: 1800000 (30 minutes)
      max-lifetime: 1800000
      pool-name: Hikari
      # Lowest acceptable validation timeout is 250 ms. Default: 5000
      validation-timeout: 5000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true