spring:
  jpa:
    database: ${herodotus.environment.database}
    # spring boot2.+后默认使用的是MyISAM引擎,增加如下配置修改为InnoDB模式，
    # 这样不会出现：Specified key was too long; max key length is 1000 bytes 问题
    database-platform: ${herodotus.environment.database-platform}
    open-in-view: true
    show-sql: ${herodotus.environment.show-sql}
    hibernate:
      ddl-auto: ${herodotus.initialization.hibernate-ddl-auto}
      #create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
      #update 如果启动时表格式不一致则更新表，原有数据保留
      #validate 项目启动表结构进行校验 如果不一致则报错
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    continue-on-error: true
    driver-class-name: ${herodotus.environment.driver-class-name}
    url: ${herodotus.environment.url}
    username: ${herodotus.environment.username}
    password: ${herodotus.environment.password}
    initialization-mode: always
    data-username: ${herodotus.environment.username}
    data-password: ${herodotus.environment.password}
    schema-username: ${herodotus.environment.username}
    schema-password: ${herodotus.environment.password}

    # 第一种方式启动的时候 Jpa 会自动创建表，import.sql 只负责创建表单后的初始化数据。第二种方式启动的时候不会创建表，需要在初始化脚本中判断表是否存在，再初始化脚本的步骤
    # refer: https://www.cnblogs.com/ityouknow/p/7089170.html
    #    schema:
    #      - classpath:sql/auth-mysql.sql
    #    data: classpath:sql/data-mysql.sql
    sql-script-encoding: UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # Lowest acceptable connection timeout is 250 ms. Default: 30000 (30 seconds)
      connection-timeout: 5000
      connection-test-query: SELECT 1
      # The minimum allowed value is 10000ms (10 seconds). Default: 600000 (10 minutes)
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 50
      # We strongly recommend setting this value, and it should be at least 30 seconds less than any database or infrastructure imposed connection time limit.
      # Default: 1800000 (30 minutes)
      max-lifetime: 1800000
      pool-name: Hikari
      # Lowest acceptable validation timeout is 250 ms. Default: 5000
      validation-timeout: 5000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true


herodotus:
  datasource:
    dynamic:
      primary: postgresql
      p6spy: true
      postgresql:
        continue-on-error: true
          driver-class-name: ${herodotus.environment.driver-class-name}
          url: ${herodotus.environment.url}
          username: ${herodotus.environment.username}
          password: ${herodotus.environment.password}
          initialization-mode: always
          data-username: ${herodotus.environment.username}
          data-password: ${herodotus.environment.password}
          schema-username: ${herodotus.environment.username}
          schema-password: ${herodotus.environment.password}
    hikari:
      # Lowest acceptable connection timeout is 250 ms. Default: 30000 (30 seconds)
      connection-timeout: 5000
      connection-test-query: SELECT 1
      # The minimum allowed value is 10000ms (10 seconds). Default: 600000 (10 minutes)
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 50
      # We strongly recommend setting this value, and it should be at least 30 seconds less than any database or infrastructure imposed connection time limit.
      # Default: 1800000 (30 minutes)
      max-lifetime: 1800000
      pool-name: Hikari
      # Lowest acceptable validation timeout is 250 ms. Default: 5000
      validation-timeout: 5000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatement: true
        elideSetAutoCommits: true
        maintainTimeStats: false