---
namespace: "default"
fileGroup: "common"
fileName: "dante-cloud-redis.yaml"
content: "spring:\r\n  data:\r\n    redis:\r\n      database: ${herodotus.environment.redis.database}\r\
  \n      host: ${herodotus.environment.redis.host}\r\n      password: ${herodotus.environment.redis.password}\r\
  \n      port: ${herodotus.environment.redis.port}\r\n      timeout: 10000\r\n  \
  \    lettuce:\r\n        pool:\r\n          max-active: 10\r\n          max-wait:\
  \ 10000\r\n          max-idle: 10\r\n          min-idle: 5\r\n    redisson:\r\n\
  \      enabled: false\r\n      single-server-config:\r\n        address: redis://${spring.data.redis.host}:${spring.data.redis.port}\r\
  \n#        password: ${spring.data.redis.password}"
version: 2
md5: "9070b48e67671ecbcaaad850d07831c1"
