---
namespace: "default"
fileGroup: "common"
fileName: "dante-cloud-database.yaml"
content: "spring:\r\n  sql:\r\n    init:\r\n      mode: ${herodotus.switch.database.init-mode}\r\
  \n      platform: ${herodotus.database-information.platform}\r\n      continue-on-error:\
  \ true\r\n      encoding: UTF-8\r\n      username: ${herodotus.environment.database.username}\r\
  \n      password: ${herodotus.environment.database.password}\r\n  datasource:\r\n\
  \    driver-class-name: ${herodotus.database-information.driver-class-name}\r\n\
  \    url: ${herodotus.database-information.url}\r\n    username: ${herodotus.environment.database.username}\r\
  \n    password: ${herodotus.environment.database.password}\r\n    type: com.zaxxer.hikari.HikariDataSource\r\
  \n    hikari:\r\n      connection-timeout: 5000\r\n      connection-test-query:\
  \ SELECT 1\r\n      idle-timeout: 600000\r\n      minimum-idle: 5\r\n      maximum-pool-size:\
  \ 50\r\n      max-lifetime: 1800000\r\n      pool-name: Hikari\r\n      validation-timeout:\
  \ 5000\r\n      data-source-properties:\r\n        prepStmtCacheSize: 250\r\n  \
  \      prepStmtCacheSqlLimit: 2048\r\n        cachePrepStmts: true\r\n  jpa:\r\n\
  \    database: ${herodotus.database-information.platform}\r\n    database-platform:\
  \ ${herodotus.database-information.platform}\r\n    open-in-view: true\r\n    show-sql:\
  \ ${herodotus.switch.database.show-sql}\r\n    hibernate:\r\n      ddl-auto: ${herodotus.switch.database.ddl-auto}\r\
  \n      naming:\r\n        physical-strategy: cn.herodotus.engine.data.jpa.hibernate.HerodotusPhysicalNamingStrategy\r\
  \n    properties:\r\n      jakarta:\r\n        persistence:\r\n          sharedCache:\r\
  \n            mode: ENABLE_SELECTIVE\r\n      hibernate:\r\n        dialect: ${herodotus.database-information.dialect}\r\
  \n        format_sql: ${herodotus.switch.database.format-sql}\r\n        show_sql:\
  \ ${herodotus.switch.database.show-sql}\r\n        generate_statistics: ${herodotus.switch.database.generate-statistics}\r\
  \n        cache:\r\n          use_query_cache: true\r\n          use_second_level_cache:\
  \ ${herodotus.switch.database.use-second-level-cache}\r\n          region:\r\n \
  \           factory_class: cn.herodotus.engine.data.jpa.hibernate.spi.cache.HerodotusRegionFactory\r\
  \n        jakarta:\r\n          cache:\r\n            missing_cache_strategy: create\r\
  \n        temp:\r\n          use_jdbc_metadata_defaults: true\r\n\r\nmybatis-plus:\r\
  \n  global-config:\r\n    banner: false\r\n    db-config:\r\n      table-underline:\
  \ true\r\n  configuration:\r\n    cache-enabled: ${herodotus.switch.database.use-second-level-cache}\r\
  \n    map-underscore-to-camel-case: true"
version: 1
md5: "296ae5171dcfcd47651cbb0fea1705e1"
