---
namespace: "default"
fileGroup: "development"
fileName: "dante-cloud-environment.yaml"
content: "herodotus:\r\n  environment:\r\n    logstash-server-addr: false\r\n    gateway-server-addr:\
  \ http://192.168.101.10:8847\r\n    database:\r\n      host: 127.0.0.1\r\n     \
  \ port: 15432\r\n      name: sherodotus\r\n      username: herodotus\r\n      password:\
  \ herodotus\r\n    redis:\r\n      host: 127.0.0.1\r\n      port: 16379\r\n    \
  \  password:\r\n      database: 6\r\n    kafka:\r\n      bootstrap-servers: 127.0.0.1:9092\r\
  \n  switch:\r\n    database:\r\n      ddl-auto: update\r\n      init-mode: never\r\
  \n      use-second-level-cache: true\r\n      show-sql: false\r\n      format-sql:\
  \ false\r\n      generate-statistics: false\r\n    swagger:\r\n      enabled: true\r\
  \n    rest:\r\n      scan:\r\n        enabled: true\r\n\r\n  log-center:\r\n   \
  \ server-addr: ${herodotus.environment.logstash-server-addr}\r\n    loggers:\r\n\
  \      cn.herodotus: debug\r\n      org.springframework.security: debug\r\n    \
  \  com.alibaba.nacos.client.naming: error\r\n      com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty:\
  \ error\r\n      org.reflections.Reflections: off\r\n      com.alibaba.nacos.client:\
  \ error\r\n      com.alibaba.nacos.common.remote.client: error\r\n      com.ulisesbocchio:\
  \ error\r\n\r\njasypt:\r\n  encryptor:\r\n    password: ${JASPYT_HOME:2bda7d3a-dba1-45a4-b08e-cbd731a0418e}"
version: 2
md5: "4219c91cbce95175353c4a67a337e7b2"
