---
namespace: "default"
fileGroup: "common"
fileName: "dante-cloud-rest.yaml"
content: "server:\r\n  error:\r\n    include-exception: true\r\n    include-message:\
  \ always\r\n    include-stacktrace: always\r\n    include-binding-errors: always\r\
  \nspring:\r\n  thymeleaf:\r\n    mode: HTML\r\n    cache: false\r\n\r\nspringdoc:\r\
  \n  api-docs:\r\n    resolve-schema-properties: true\r\n  swagger-ui:\r\n    enabled:\
  \ ${herodotus.switch.swagger.enabled}\r\n    disable-swagger-default-url: true\r\
  \n    operations-sorter: method\r\n    show-common-extensions: true\r\n    show-extensions:\
  \ true\r\n    oauth:\r\n      use-pkce-with-authorization-code-grant: true\r\n \
  \     app-name: ${spring.application.name}\r\n\r\nmanagement:\r\n  endpoints:\r\n\
  \    web:\r\n      exposure:\r\n        include: '*'\r\n  endpoint:\r\n    health:\r\
  \n      show-details: ALWAYS\r\n\r\nfeign:\r\n  client:\r\n    config:\r\n     \
  \ default:\r\n        connectTimeout: 5000\r\n        readTimeout: 5000\r\n  sentinel:\r\
  \n    enabled: true\r\n  hystrix:\r\n    enabled: false\r\n\r\nribbon:\r\n  ReadTimeout:\
  \ 5000\r\n  ConnectTimeout: 2000\r\n  MaxAutoRetries: 1\r\n  OkToRetryOnAllOperations:\
  \ true\r\n  MaxAutoRetriesNextServer: 1\r\n  http:\r\n    client:\r\n      enabled:\
  \ false\r\n  okhttp:\r\n    enabled: true\r\n  eager-load:\r\n    enabled: true\r\
  \n  nacos:\r\n    enabled: false\r\n\r\nherodotus:\r\n  rest:\r\n    scan:\r\n \
  \     enabled: ${herodotus.switch.rest.scan.enabled}"
version: 1
md5: "bb094837af79cdf3e6092c833210bdfb"
