---
namespace: "default"
fileGroup: "common"
fileName: "dante-cloud-social.yaml"
content: "herodotus:\r\n  sms:\r\n    enabled: true\r\n    sandbox: true\r\n    test-code:\
  \ 123456\r\n    default-channel: aliyun\r\n    aliyun:\r\n      enabled: true\r\n\
  \      access-key-id: xxxxxx\r\n      access-key-secret: xxxxxxx\r\n      region-id:\
  \ cn-shanghai\r\n      sign-name: helloword\r\n      version: 2017-05-25\r\n   \
  \   templates: { \"VERIFICATION_CODE\": \"SMS_222222222\" }\r\n  access:\r\n   \
  \ justauth:\r\n      enabled: true\r\n      configs:\r\n        GITEE:\r\n     \
  \     client-id: 7c1623d76f3909757912338688cae8a061e241b5607\r\n          client-secret:\
  \ 8c343cad9ca732d54242f002d254239e17b68ca\r\n          redirect-uri: http://192.168.101.10:3000/social/oauth2/callback/GITEE"
version: 1
md5: "ac74cd40984519200344b7403d9d4c0c"
