global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10m
rule_files:
  - "/etc/prometheus/rules/*.rules"
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - localhost:9090
        labels:
          instance: prometheus

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets:
          - 192.168.101.10:9091
        labels:
          instance: pushgateway

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.101.10:9100
        labels:
          instance: dashboard-linux

  - job_name: 'windows-exporter'
    static_configs:
      - targets:
          - 192.168.101.10:9182
        labels:
          instance: dashboard-windows

  - job_name: 'emqx'
    metrics_path: /api/v5/prometheus/stats
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets:
          - 192.168.101.10:18083
        labels:
          instance: dashboard-emqx

