eurynome:
  platform:
    uaa-server-addr: ${eurynome.platform.gateway-server-addr}/eurynome-cloud-platform-uaa
    upms-server-addr: ${eurynome.platform.gateway-server-addr}/eurynome-cloud-upms-rest
    access-token-uri: ${eurynome.platform.uaa-server-addr}/oauth/token
    user-authorization-uri: ${eurynome.platform.uaa-server-addr}/oauth/authorize
    token-info-uri: ${eurynome.platform.uaa-server-addr}/oauth/check_token
    user-info-uri: ${eurynome.platform.uaa-server-addr}/current/user
    scope: all
    client-id: 010e659a-4005-4610-98f6-00b822f4758e
    client-secret: 04165a07-cffd-45cf-a20a-1c2a69f65fb1
    jwt-signing-key: eurynome-cloud
  swagger2:
    access-token-uri: ${eurynome.platform.access-token-uri}
    client-id: ${eurynome.platform.client-id}
    client-secret: ${eurynome.platform.client-secret}
    enabled: true
    scope: ${eurynome.platform.scope}
    user-authorization-uri: ${eurynome.platform.user-authorization-uri}