spring:
  redis:
    database: 0
    host: 127.0.0.1
  #  password: ENC(oQr1JlWshemWU2hn35HZVNIPoJdjPx/N)
    port: 6379
    timeout: 10000
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 10
        max-wait: 10000
        # 最大空闲连接数 默认8
        max-idle: 10
        # 最小空闲连接数 默认0
        min-idle: 5