herodotus:
  platform:
    gateway-server-addr: http://localhost:8847
    auth-server-addr: http://localhost:8846
    access-token-uri: ${herodotus.platform.auth-server-addr}/oauth/token
    user-authorization-uri: ${herodotus.platform.auth-server-addr}/oauth/authorize
    token-info-uri: ${herodotus.platform.auth-server-addr}/oauth/check_token
    user-info-uri: ${herodotus.platform.auth-server-addr}/current/user
    scope: all
    client-id: 1552294656514
    client-secret: 123456
    jwt-signing-key: herodotus-cloud
    upms-server-addr: http://localhost:7070
  swagger2:
    access-token-uri: ${herodotus.platform.access-token-uri}
    client-id: ${herodotus.platform.client-id}
    client-secret: ${herodotus.platform.client-secret}
    enabled: true
    scope: ${herodotus.platform.scope}
    user-authorization-uri: ${herodotus.platform.user-authorization-uri}