herodotus:
  environment:
    logstash-server-addr: false
    gateway-server-addr: http://localhost:8847
    database:
      host: 127.0.0.1
      port: 13306
      name: herodotus
      username: ENC(VQOHWBUv8CXJE50zyMEhCozzElZhNbJ8suinU7Ph651G1xl4QPweElrhtXP4V0T8)
      password: ENC(VQOHWBUv8CXJE50zyMEhCozzElZhNbJ8suinU7Ph651G1xl4QPweElrhtXP4V0T8)
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 6
    kafka:
      bootstrap-servers: 127.0.0.1:9092
  switch:
    database:
      ddl-auto: update
      init-mode: never
      use-second-level-cache: true
      show-sql: false
      format-sql: false
      generate-statistics: false
    swagger:
      enabled: true
    redisson:
      enabled: false
    rest:
      scan:
        enabled: true

  log-center:
    server-addr: ${herodotus.environment.logstash-server-addr}
    loggers:
      cn.herodotus.eurynome: debug
      org.springframework.security: debug
      com.alibaba.nacos.client.naming: error
      com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty: error
      # 关闭不必要的日志
      org.reflections.Reflections: off
      com.alibaba.nacos.client: error
      com.alibaba.nacos.common.remote.client: error
      com.ulisesbocchio: error

  platform:
    # 服务退出时清除多级缓存中Redis中的数据，正式环境建议关闭
    cache:
      clear-remote-on-exit: true

jasypt:
  encryptor:
    password: ${JASPYT_HOME:2bda7d3a-dba1-45a4-b08e-cbd731a0418e}